#!/bin/bash

BUILD_DIR='desktop'

mkdir -p $BUILD_DIR/obj/
mkdir -p $BUILD_DIR/obj/source/
mkdir -p $BUILD_DIR/dep/
mkdir -p $BUILD_DIR/dep/source/

DIRS=$(cd $BUILD_DIR/source; find -L . -type d)

cd $BUILD_DIR/obj/source
mkdir -p $DIRS
cd ../../../

cd $BUILD_DIR/dep/source
mkdir -p $DIRS
cd ../../../

cd $BUILD_DIR
make
